# Generated by Django 3.2.4 on 2021-06-08 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('virtualroom', '0003_auto_20210608_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='information.section', verbose_name='Sección')),
                ('virtualroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='virtualroom.virtualroom', verbose_name='Clase virtual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('file', models.FileField(upload_to='topics/%Y/%m/%d')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.topic', verbose_name='archivos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
