# Generated by Django 3.2.6 on 2021-08-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20210824_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media/topics/%Y/%m/%d'),
        ),
    ]
