# Generated by Django 3.2.4 on 2021-06-07 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('photo', models.ImageField(blank=True, upload_to='users/', verbose_name='Foto')),
                ('web_page', models.CharField(blank=True, max_length=50, verbose_name='Página web')),
                ('facebook_link', models.CharField(blank=True, max_length=50, verbose_name='Facebook')),
                ('twitter_link', models.CharField(blank=True, max_length=50, verbose_name='Twitter')),
                ('instagram_link', models.CharField(blank=True, max_length=50, verbose_name='Instagram')),
                ('linkedin_link', models.CharField(blank=True, max_length=50, verbose_name='Linkedin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='information', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
