# Generated by Django 3.2.4 on 2021-06-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Linkedin'),
        ),
    ]
