# Generated by Django 3.2.4 on 2021-06-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_personalinformation_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='ocupation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ocupación Actual'),
        ),
        migrations.AddField(
            model_name='personalinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono Móvil'),
        ),
    ]
