# Generated by Django 3.2.4 on 2021-08-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20210607_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinformation',
            options={'verbose_name': 'Información del usuario', 'verbose_name_plural': 'Información de los usuarios'},
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='creation_date',
            field=models.DateTimeField(editable=False, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='last_modified',
            field=models.DateTimeField(editable=False, verbose_name='Última modificación'),
        ),
    ]
