# Generated by Django 3.2.6 on 2021-08-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210824_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/users/', verbose_name='Foto'),
        ),
    ]
