# Generated by Django 3.2.7 on 2021-09-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_alter_personalinformation_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='photo',
            field=models.ImageField(upload_to='users/', verbose_name='Foto'),
        ),
    ]
