# Generated by Django 3.2.4 on 2021-06-07 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('state', models.IntegerField(choices=[(0, 'No aceptado'), (1, 'Pendiente que acepte el estudiante'), (2, 'Pendiente que acepte el profesor'), (3, 'Aceptado'), (4, 'Expulsado'), (5, 'Abandonó la clase virtual')])),
                ('rol', models.IntegerField(choices=[(0, 'Estudiante'), (1, 'Profesor')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VirtualRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False)),
                ('last_modified', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
                ('is_private', models.BooleanField(verbose_name='Es privado')),
                ('photo', models.ImageField(blank=True, upload_to='virtualrooms/', verbose_name='Foto')),
                ('status', models.IntegerField(choices=[(0, 'Clase Virtual Activada'), (1, 'Clase Virtual Archivada')], default=0)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtualroomscreated', to=settings.AUTH_USER_MODEL, verbose_name='Creador de la Clase Virtual')),
                ('participants', models.ManyToManyField(related_name='virtualrooms', through='virtualroom.Enrollment', to=settings.AUTH_USER_MODEL, verbose_name='Estudiantes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='virtualroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='virtualroom.virtualroom', verbose_name='Clase virtual'),
        ),
    ]
