# Generated by Django 3.2.4 on 2021-06-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualroom',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='virtualroom',
            name='status',
            field=models.IntegerField(choices=[(0, 'Clase Virtual Activada'), (1, 'Clase Virtual Archivada')], default=0, verbose_name='Estado'),
        ),
    ]
