# Generated by Django 3.2.7 on 2021-09-14 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualroom', '0005_alter_virtualroom_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualroom',
            name='photo',
            field=models.ImageField(upload_to='virtualrooms/', verbose_name='Foto'),
        ),
    ]
