# Generated by Django 3.2.4 on 2021-06-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualroom', '0002_auto_20210607_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='rol',
            field=models.IntegerField(choices=[(0, 'Estudiante'), (1, 'Profesor')], default=0),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='state',
            field=models.IntegerField(choices=[(0, 'No aceptado / Cancelado'), (1, 'Pendiente que acepte el estudiante'), (2, 'Pendiente que acepte el profesor'), (3, 'Aceptado'), (4, 'Expulsado'), (5, 'Abandonó la clase virtual')]),
        ),
        migrations.AlterField(
            model_name='virtualroom',
            name='photo',
            field=models.ImageField(upload_to='virtualrooms/', verbose_name='Foto'),
        ),
    ]
